apiVersion: v1
kind: Namespace
metadata:
  name: mailhog
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-mailhog
  namespace: mailhog
data:
  tls.crt: Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOiAyMCAoMHgxNCkKICAgICAgICBTaWduYXR1cmUgQWxnb3JpdGhtOiBzaGEyNTZXaXRoUlNBRW5jcnlwdGlvbgogICAgICAgIElzc3VlcjogQz1DQSwgU1Q9T250YXJpbywgTz1DZW50cmVvbiBzb2Z0d2FyZSBMdGQuLCBDTj1DTlRSLVBPUlQtQTA5MS9lbWFpbEFkZHJlc3M9c3VwcG9ydEBjZW50cmVvbi5jb20KICAgICAgICBWYWxpZGl0eQogICAgICAgICAgICBOb3QgQmVmb3JlOiBNYXkgMjggMjE6MjU6MzIgMjAyNCBHTVQKICAgICAgICAgICAgTm90IEFmdGVyIDogTWF5IDI4IDIxOjI1OjMyIDIwMjUgR01UCiAgICAgICAgU3ViamVjdDogQz1DQSwgU1Q9T250YXJpbywgTz1DZW50cmVvbiBzb2Z0d2FyZSBMdGQuLCBPVT1TYWxlcywgQ049azhzLmludC5jZW50cmVvbi5jb20KICAgICAgICBTdWJqZWN0IFB1YmxpYyBLZXkgSW5mbzoKICAgICAgICAgICAgUHVibGljIEtleSBBbGdvcml0aG06IHJzYUVuY3J5cHRpb24KICAgICAgICAgICAgICAgIFJTQSBQdWJsaWMtS2V5OiAoMjA0OCBiaXQpCiAgICAgICAgICAgICAgICBNb2R1bHVzOgogICAgICAgICAgICAgICAgICAgIDAwOmRkOjkwOjE1OjMxOmMzOjZjOjNmOjEyOjdmOmY4OmUzOjU2OjBmOjg5OgogICAgICAgICAgICAgICAgICAgIDc1OjViOjA5OmI2OjM0Ojc4OjRmOmU0OmM3OjlkOjZiOmViOjkyOmIxOmQwOgogICAgICAgICAgICAgICAgICAgIDUwOmRhOjAxOjMzOjBmOmI1OmVkOmE5OjNiOjRlOjhiOjM2OmY1OjQ2OjIyOgogICAgICAgICAgICAgICAgICAgIDQ1OmZhOmY4OmE5OjY4OmFkOjQzOmIxOjk2OmIxOjczOmEyOjAwOmFiOjBlOgogICAgICAgICAgICAgICAgICAgIDhjOjlkOjZmOmU3OmFhOjU0OmMxOjAxOmNhOmJkOmZmOmY5Ojc5OjZhOmIyOgogICAgICAgICAgICAgICAgICAgIDZhOjkwOmY0OjEzOjdhOjA3OmQ4OmRmOjM4OmUzOmQ2OmRlOjlkOmZiOmI1OgogICAgICAgICAgICAgICAgICAgIDkwOjUyOjMyOjllOmM5OjQ1OjMxOmExOmU0OmE4OjJiOjQ1OmQwOjU4OjI1OgogICAgICAgICAgICAgICAgICAgIDJiOjExOmI0OmE1OjVhOjFhOjNiOjdmOjRmOjFlOjEyOjg1OjU4OjRlOjkyOgogICAgICAgICAgICAgICAgICAgIDg4OjFmOjQyOjZiOmFlOjk5OmE5OjE5OmYwOjYyOmVjOjQ4OmIzOjFjOmViOgogICAgICAgICAgICAgICAgICAgIDI2OjI5OjQxOjBiOjkyOjk5OmYyOmJiOjY1OjUxOjQwOjkxOmE0OjUwOjkxOgogICAgICAgICAgICAgICAgICAgIDEwOjc0OjQxOjBlOjVkOjViOmRiOmIyOmZkOjRiOjcwOmZhOjNmOmFmOjkwOgogICAgICAgICAgICAgICAgICAgIGYyOjc4OjZhOjU0OjAyOmM5OjFjOjk0OmMyOjdhOmI3OjcxOmJjOmJjOmFlOgogICAgICAgICAgICAgICAgICAgIDkyOmJiOjM2OjdlOjM0Ojc2OjhiOmI5OmMxOjA3Ojg1OjUzOmFmOjczOjBkOgogICAgICAgICAgICAgICAgICAgIDNkOmY3OmU5OjFiOjhjOjAyOmRlOjc3OmJkOjYyOjdhOjA1OjcxOjRkOmI2OgogICAgICAgICAgICAgICAgICAgIDI0OjM2OjM1OmJkOjg3OjVlOjkwOjMzOjJhOmM5OmU1OmY0OjQ1OjdiOmE5OgogICAgICAgICAgICAgICAgICAgIGY2OjZmOmNkOjRiOjZkOjllOjkwOjg3OmExOjRkOjA5OmNhOmYyOmY4OmIzOgogICAgICAgICAgICAgICAgICAgIDU3OjgwOmY1OjIxOmU5OmZlOmYzOmJjOjU0OjViOjJlOmM2OmZlOjg3OjU1OgogICAgICAgICAgICAgICAgICAgIGEzOmFmCiAgICAgICAgICAgICAgICBFeHBvbmVudDogNjU1MzcgKDB4MTAwMDEpCiAgICAgICAgWDUwOXYzIGV4dGVuc2lvbnM6CiAgICAgICAgICAgIFg1MDl2MyBBdXRob3JpdHkgS2V5IElkZW50aWZpZXI6IAogICAgICAgICAgICAgICAgRGlyTmFtZTovQz1DQS9TVD1PbnRhcmlvL089Q2VudHJlb24gc29mdHdhcmUgTHRkLi9DTj1DTlRSLVBPUlQtQTA5MS9lbWFpbEFkZHJlc3M9c3VwcG9ydEBjZW50cmVvbi5jb20KICAgICAgICAgICAgICAgIHNlcmlhbDoxNTowNjpGNzo1QTo1RjpBNjozRTpCMTo5NzpCMTpBNjo0NDoxQjoyOTozOTo1Njo2NToyNToxNDpENAoKICAgICAgICAgICAgWDUwOXYzIEJhc2ljIENvbnN0cmFpbnRzOiAKICAgICAgICAgICAgICAgIENBOkZBTFNFCiAgICAgICAgICAgIFg1MDl2MyBLZXkgVXNhZ2U6IAogICAgICAgICAgICAgICAgRGlnaXRhbCBTaWduYXR1cmUsIE5vbiBSZXB1ZGlhdGlvbiwgS2V5IEVuY2lwaGVybWVudCwgRGF0YSBFbmNpcGhlcm1lbnQKICAgICAgICAgICAgWDUwOXYzIFN1YmplY3QgS2V5IElkZW50aWZpZXI6IAogICAgICAgICAgICAgICAgREQ6RUQ6NDQ6QjU6NzI6M0I6QTg6QjA6NTY6Mzk6RTg6MTA6ODc6N0U6REI6RTk6NEE6QkU6NTI6OEUKICAgICAgICAgICAgWDUwOXYzIFN1YmplY3QgQWx0ZXJuYXRpdmUgTmFtZTogCiAgICAgICAgICAgICAgICBJUCBBZGRyZXNzOjE3Mi4xNi41LjIyMywgRE5TOmNlbnRyYWwuazhzLmNlbnRyZW9uLmNvbSwgRE5TOm1haWxob2cuazhzLmNlbnRyZW9uLmNvbQogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICAgNmI6NWU6MmY6OTc6NDY6Yjc6NDQ6YTE6Y2I6NTY6OWM6YTQ6ZTc6M2Q6MjQ6YmU6NDU6Yjg6CiAgICAgICAgIDE1OjhlOjc0OmI1OmU3OmEwOmQ4OmEwOjExOjk0OjM2Ojk0Ojc4OjJhOmJlOjNkOmJlOjAzOgogICAgICAgICAyYTo0NzpmNDpiZDpiZDpmMzo3Nzo1Mjo1Nzo2Nzo3MzoyMzo0Mjo2NToyODo2MTplZjplYjoKICAgICAgICAgNmI6ZjA6MTM6ODI6MDI6M2E6YmM6OTU6NmY6MDk6YTA6OWM6Yjg6OGE6ZjY6YWM6ZmY6Zjc6CiAgICAgICAgIDZkOjdkOjNiOjQ2OjRmOmFhOjc2OjI0OmJlOmVkOmM5OmFlOjBlOmNhOmZlOmI3OjUwOjFlOgogICAgICAgICBkNjpkMTplZjoxYjo4MDo2YTo5Yjo2MzpjZDo5OTo4NTpkYzo0ZDozYjo5ZTo4MDpjNjo2ZjoKICAgICAgICAgZDE6YzM6NGQ6ZWE6MTY6YjU6ODE6NmI6MWE6YTE6MWU6NGE6YzY6NTU6N2M6Mjc6YjA6NWY6CiAgICAgICAgIDc2OmU2OjAzOmJiOmRlOmRmOjRkOmU0OjI4OjZhOmUyOjNkOmE0OjBjOjFhOjkwOjNiOmQ2OgogICAgICAgICBhNDpmMjo2MTozNjo3YTozMDpjOTozNDpiMDpjMTowZTo0NTpkZDplOTpiMDoyYTo3YTowNDoKICAgICAgICAgNzU6NWU6Njc6ZjQ6OTU6MTk6ZGU6NDU6MDY6ZDI6NmU6MDE6YTI6YTg6MmE6ZDU6ZjI6ZmM6CiAgICAgICAgIDU0OjljOjZmOjVlOmY5OjQ1OmFkOmY4OmNmOmJiOjM3OmUyOjhlOjJmOjNjOmQxOjRmOmRlOgogICAgICAgICA4NTowZjpmMTowNjoyYjpkOTo2ZDoyYzo1MDoyOTo4ZTo0ZDpkNzo4ZTplMTpjYzo0NzplNDoKICAgICAgICAgMDI6ZDI6MzI6ZDY6YmM6MDM6MGM6NWE6NDg6OTc6OTE6NWI6ZTc6MzM6ZTQ6ZGQ6NzE6MTM6CiAgICAgICAgIDczOjQyOjVmOjVhOjE3OjUzOmJiOjFhOjdhOmQyOjg1OjFmOjk4OjM5OjU5OjUwOmYzOmQ3OgogICAgICAgICA4OTo4Nzo5ZDplYTo3ZjowZToyMjowODoyZjowNTplMjoxMjo1MzphNzplYjo0ZTo0MzpiYjoKICAgICAgICAgZWM6NTY6MTM6MzA6M2M6MDA6NTU6MGI6ZWM6OWI6Yjg6MTQ6YTY6ZTI6N2M6YjU6OWE6YjE6CiAgICAgICAgIDI0OjhlOmEzOjJkOjU5OjEyOjA1OmRmOjg4OjliOjdiOjE0OmEwOmQwOmMyOmFiOjVmOjQzOgogICAgICAgICAyNTo0NjplZDo2Mjo3OToyOTpiZTo3ZDoyYjplYzozYzo2MjoxMDo2MDo5Njo1Zjo4ZDoxZDoKICAgICAgICAgNjk6NjE6ZTg6MTA6NWI6YjQ6ODI6ZmI6OGM6MjQ6OGQ6YmI6MDE6ZDU6Yzg6ZjQ6ZWM6OWQ6CiAgICAgICAgIGI5OjgyOjllOjEyOmY4OmQ4OmE1OjU1OmNkOmIzOmFkOjg5OjlmOjE1OmRkOjE1OjA1OjkxOgogICAgICAgICBlYTo2OTphODoxMjo4ZDoxOTpjYzphMTo3NTpkNzo2ZTphODo3OTphODo1MTowNjoxNzowYToKICAgICAgICAgNTM6OTM6M2M6OGM6NWY6NGI6MjM6ODQ6YTU6Nzk6MzI6NDE6YTU6YmE6YmE6YWE6NWY6ODg6CiAgICAgICAgIDQ2OjcyOjA1OjNmOjkzOmMxOjE1OjViOmFhOjU5OjRkOmZlOjk3OmY0OjMyOjBlOjk1OjBhOgogICAgICAgICAzMTpiMTo1NDowMjpjNjpkYzphYjo3ZjplMTpmYzo0NTo0MDo0OToxYTo5NTphMTo4MTo4ZToKICAgICAgICAgMzY6NWI6ZDc6NDk6ZTQ6Yzg6ZDQ6NjA6YTE6YWU6YTM6OTA6NWU6ODg6MjY6ZGY6MWM6NWI6CiAgICAgICAgIGI5OmExOmVhOmUzOjFkOmNjOjA5OmZhOjZkOjk2OmM5OjQzOjkwOmQ3OjBlOjQ2OmEyOmU1OgogICAgICAgICA4YTo5YzphZTphNDo3MDo1NTozODpmZTowNTowNzo4Mjo4Yjo5YTpmMzphYzozMDpmYTowYjoKICAgICAgICAgYjQ6OTQ6MmY6ZWU6ZmM6NTQ6OTQ6YzM6NjI6N2Q6ZWY6NDM6Yzk6ZGI6NmI6MDA6ZGE6N2Q6CiAgICAgICAgIDU1OmE2OjdjOmZlOmQxOjhhOmNmOjFmCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlGbERDQ0EzeWdBd0lCQWdJQkZEQU5CZ2txaGtpRzl3MEJBUXNGQURCK01Rc3dDUVlEVlFRR0V3SkRRVEVRCk1BNEdBMVVFQ0F3SFQyNTBZWEpwYnpFZk1CMEdBMVVFQ2d3V1EyVnVkSEpsYjI0Z2MyOW1kSGRoY21VZ1RIUmsKTGpFWE1CVUdBMVVFQXd3T1EwNVVVaTFRVDFKVUxVRXdPVEV4SXpBaEJna3Foa2lHOXcwQkNRRVdGSE4xY0hCdgpjblJBWTJWdWRISmxiMjR1WTI5dE1CNFhEVEkwTURVeU9ESXhNalV6TWxvWERUSTFNRFV5T0RJeE1qVXpNbG93CmJ6RUxNQWtHQTFVRUJoTUNRMEV4RURBT0JnTlZCQWdNQjA5dWRHRnlhVzh4SHpBZEJnTlZCQW9NRmtObGJuUnkKWlc5dUlITnZablIzWVhKbElFeDBaQzR4RGpBTUJnTlZCQXNNQlZOaGJHVnpNUjB3R3dZRFZRUUREQlJyT0hNdQphVzUwTG1ObGJuUnlaVzl1TG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFOMlFGVEhEYkQ4U2YvampWZytKZFZzSnRqUjRUK1RIbld2cmtySFFVTm9CTXcrMTdhazdUb3MyOVVZaVJmcjQKcVdpdFE3R1dzWE9pQUtzT2pKMXY1NnBVd1FIS3ZmLzVlV3F5YXBEMEUzb0gyTjg0NDliZW5mdTFrRkl5bnNsRgpNYUhrcUN0RjBGZ2xLeEcwcFZvYU8zOVBIaEtGV0U2U2lCOUNhNjZacVJud1l1eElzeHpySmlsQkM1S1o4cnRsClVVQ1JwRkNSRUhSQkRsMWIyN0w5UzNENlA2K1E4bmhxVkFMSkhKVENlcmR4dkx5dWtyczJmalIyaTduQkI0VlQKcjNNTlBmZnBHNHdDM25lOVlub0ZjVTIySkRZMXZZZGVrRE1xeWVYMFJYdXA5bS9OUzIyZWtJZWhUUW5LOHZpegpWNEQxSWVuKzg3eFVXeTdHL29kVm82OENBd0VBQWFPQ0FTb3dnZ0VtTUlHbkJnTlZIU01FZ1o4d2daeWhnWU9rCmdZQXdmakVMTUFrR0ExVUVCaE1DUTBFeEVEQU9CZ05WQkFnTUIwOXVkR0Z5YVc4eEh6QWRCZ05WQkFvTUZrTmwKYm5SeVpXOXVJSE52Wm5SM1lYSmxJRXgwWkM0eEZ6QVZCZ05WQkFNTURrTk9WRkl0VUU5U1ZDMUJNRGt4TVNNdwpJUVlKS29aSWh2Y05BUWtCRmhSemRYQndiM0owUUdObGJuUnlaVzl1TG1OdmJZSVVGUWIzV2wrbVByR1hzYVpFCkd5azVWbVVsRk5Rd0NRWURWUjBUQkFJd0FEQUxCZ05WSFE4RUJBTUNCUEF3SFFZRFZSME9CQllFRk4zdFJMVnkKTzZpd1Zqbm9FSWQrMitsS3ZsS09NRU1HQTFVZEVRUThNRHFIQkt3UUJkK0NHR05sYm5SeVlXd3Vhemh6TG1ObApiblJ5Wlc5dUxtTnZiWUlZYldGcGJHaHZaeTVyT0hNdVkyVnVkSEpsYjI0dVkyOXRNQTBHQ1NxR1NJYjNEUUVCCkN3VUFBNElDQVFCclhpK1hScmRFb2N0V25LVG5QU1MrUmJnVmpuUzE1NkRZb0JHVU5wUjRLcjQ5dmdNcVIvUzkKdmZOM1VsZG5jeU5DWlNoaDcrdHI4Qk9DQWpxOGxXOEpvSnk0aXZhcy8vZHRmVHRHVDZwMkpMN3R5YTRPeXY2MwpVQjdXMGU4YmdHcWJZODJaaGR4Tk81NkF4bS9SdzAzcUZyV0JheHFoSGtyR1ZYd25zRjkyNWdPNzN0OU41Q2hxCjRqMmtEQnFRTzlhazhtRTJlakRKTkxEQkRrWGQ2YkFxZWdSMVhtZjBsUm5lUlFiU2JnR2lxQ3JWOHZ4VW5HOWUKK1VXdCtNKzdOK0tPTHp6UlQ5NkZEL0VHSzlsdExGQXBqazNYanVITVIrUUMwakxXdkFNTVdraVhrVnZuTStUZApjUk56UWw5YUYxTzdHbnJTaFIrWU9WbFE4OWVKaDUzcWZ3NGlDQzhGNGhKVHArdE9RN3ZzVmhNd1BBQlZDK3liCnVCU200bnkxbXJFa2pxTXRXUklGMzRpYmV4U2cwTUtyWDBNbFJ1MWllU20rZlN2c1BHSVFZSlpmalIxcFllZ1EKVzdTQys0d2tqYnNCMWNqMDdKMjVncDRTK05pbFZjMnpyWW1mRmQwVkJaSHFhYWdTalJuTW9YWFhicWg1cUZFRwpGd3BUa3p5TVgwc2poS1Y1TWtHbHVycXFYNGhHY2dVL2s4RVZXNnBaVGY2WDlESU9sUW94c1ZRQ3h0eXJmK0g4ClJVQkpHcFdoZ1k0Mlc5ZEo1TWpVWUtHdW81QmVpQ2JmSEZ1NW9lcmpIY3dKK20yV3lVT1ExdzVHb3VXS25LNmsKY0ZVNC9nVUhnb3VhODZ3dytndTBsQy91L0ZTVXcySjk3MFBKMjJzQTJuMVZwbnorMFlyUEh3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBM1pBVk1jTnNQeEovK09OV0Q0bDFXd20yTkhoUDVNZWRhK3VTc2RCUTJnRXpEN1h0CnFUdE9pemIxUmlKRit2aXBhSzFEc1pheGM2SUFxdzZNblcvbnFsVEJBY3E5Ly9sNWFySnFrUFFUZWdmWTN6amoKMXQ2ZCs3V1FVaktleVVVeG9lU29LMFhRV0NVckViU2xXaG83ZjA4ZUVvVllUcEtJSDBKcnJwbXBHZkJpN0VpegpIT3NtS1VFTGtwbnl1MlZSUUpHa1VKRVFkRUVPWFZ2YnN2MUxjUG8vcjVEeWVHcFVBc2tjbE1KNnQzRzh2SzZTCnV6WitOSGFMdWNFSGhWT3ZjdzA5OStrYmpBTGVkNzFpZWdWeFRiWWtOalc5aDE2UU15cko1ZlJGZTZuMmI4MUwKYlo2UWg2Rk5DY3J5K0xOWGdQVWg2Zjd6dkZSYkxzYitoMVdqcndJREFRQUJBb0lCQUdsa0RoRGJ5bk8rRXcySwo1ZmNDQmNiR09kdC9sMUZWK25YSldzQW1QUzlWL3Juc2FoNWp6WnEvQzdET3dNYiszV2FqZEYzWE5wV3dhK3p5ClFNVHE1Q0hMcXZ0MU95ZTF2YUdaT01PMnRrVUgwb3RyL2tUSkpCRUZicDhLNFNrUU51bXhZS1VrMGxQN2FoOUQKOUp1RmV1TzErTElLcDlUSU11UGJybWtoUXFUSkp5Y3JtOW9HTkhpYS8yeC96WnBkUjNKczZHY0JuWTFvemtNOQpNUVlCMzI5c0FZRVBXYllzb2g3TCtsa3NKYTF1aGtJUVJsU0prS29EbUtPNk5PZThZZDBsZjk4VW5LQXZFZ0lBCk9Kb3A3ZlFrM0hobnRUZko0RlVJMTBhaFFFdWxIQWpoTTk0Q2kwKytHcXVkUElRamRudHdtbjA4aExCRXMzaXAKdndlNGhQRUNnWUVBOTN4dGtxWkE5RlRUaEtmdDEwV2Y4dDJyNUlLeEluUk9GQ25zcnV1bCtXemt5SnpmZGhqWQpYRjR2VmxsNVlnU1N5M3RJaFRUUDQ0Um4rdXlUaHZzdHk3NXdSYkVkSmpHSnlDeFdCY3hiOUVZQm9mcnJuUlhyCldKdURVRHdCd0VKV0pETG1TRzkyRkQ1Ylg0WjNCa29ZTDEra0oyNXlQVEloQjhzb0t0WHV6ZlVDZ1lFQTVTOWEKVnBtUXMxdlkvUmRScExKM2RIN1F0QS9SRSs1QjhrU05jU3l2bGxRMFZhUThPcDJpS0xDR0RtT1J3L1JpWXNHcQpUcmlzNDR3NzhJck5PRUlpaHA1VXd3WitOYnFPT1I3MWJKY0t1ODFERkhYQjRIV3BleHFQVUNZQ2JYZXhxNWVxCjJEczRENXRNazNxd2liL1Z3SllRc2hxR2NKRkFXaURRY2ppajRKTUNnWUF4Z2N5UmgzeDY0L1VrRmt1M3dvL0sKajVseExzdXNic09udVBORjBwSHpJVnRxM2lhOWd4N1U2MnBneGFsSWVFMjlNcjVCRjExMnorZlZCRHBHeUR4VApBNWVGK1hZeFM3dWFOWFJIMktlVVorU3Z1SGdsaGxyNzhMQUYvdHNDME1KV24yLzlrWDUzY2pucEZBYi9WUmNkCmN1NXRqT1NCWldQQ0lWdTVwZTROZVFLQmdRQzdRV3h6YzNkNlJLSlBjRDBoN3p1UThJaS9obWpTK3duZzA4Z3AKWDFSNzVJTDZNbjJQZXZwaWVwQ2RzeGNIWDJiL3Y3TFNMU3Y5bzdmWnV0OGdoMURFWXh0b1dhYkhhWTBJK05XWQpDdlVYS3dnUzhJQWZVS1BRVkl3aDlWeG9hcks5TytlNFV2SmtOZ1JrUDR0OGtVUXAzYkw0Z3BtejRjb05tZUFXClkxYnFod0tCZ1FDZGcyR0s5R0hsbnVxakRiZGw2WWVSSmRKZ2VtQkZIWVF2bjVDS3hGUUFHdlBBSzhJMUdzS0EKaC9rMmQ0cSsycnlLcHdmNG9UdG8xNkwxV3JERHJzQ2JCTkdEWUZLdFpYRHYxejZreUc2NHZBM3dVYmpYbUhmaApJTUZLTDRaNTBET0k0V3RFT04xK3RxdEx5ZnJhYjh2bldxQVd1ckt3TFdKM3hWMUhzTW8xcGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailhog-ingress
  namespace: mailhog
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
  labels:
    name: mailhog-ingress
spec:
  tls:
  - hosts: 
    - mailhog.k8s.centreon.com
    secretName: tls-mailhog
  ingressClassName: nginx
  rules:
  - host: mailhog.k8s.centreon.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mailhog-web
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-web
  namespace: mailhog
spec: 
  selector:
    app: mailhog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-smtp
  namespace: mailhog
spec:
  selector:
    app: mailhog
  ports:
    - protocol: TCP
      port: 25
      targetPort: 1025
  type: LoadBalancer
  externalIPs:
    - 172.16.5.223
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 1025
          protocol: TCP
        - containerPort: 8025
          protocol: TCP

