x-common-variables: &common-variables
  TZ: America/Toronto
  SMTP_ADDR: <SMTP_ADDR:PORT>
  MYSQL_ROOT_PASSWORD: centreon
  VERSION: "24.04"
  CENTREON_DB_PASSWORD: centreon

volumes:
  centreon-share:
    name: centreon-share
  centreon-img:
    name: centreon-img
  centreon-etc:
    name: centreon-etc
  centreon-var:
    name: centreon-var
  centreon-cache:
    name: centreon-cache
  broker-etc:
    name: broker-etc
  broker-log:
    name: broker-log
  broker-module:
    name: broker-module
  centengine-etc:
    name: centengine-etc
  gorgone-etc:
    name: gorgone-etc
  gorgone-cache:
    name: gorgone-cache
  gorgone-var:
    name: gorgone-var
  centengine-log:
    name: centengine-log
  centengine-var:
    name: centengine-var
  centreon-bin:
    name: centreon-bin
  centplugin:
    name: centplugin
  centreon-pack:
    name: centreon-pack

networks:
  centreon_net:
    name: centreon_net
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.0/24"


services:
  cbd:
    build:
      context: broker
      args:
        <<: *common-variables
    image: tpo76/broker:24.04.0
    container_name: cbd
    hostname: cbd
    restart: always
    ports:
      - 5669:5669
    networks:
      - centreon_net
    volumes:
      - centreon-var:/var/lib/centreon:z,rw
      - broker-etc:/etc/centreon-broker:z,rw
      - broker-log:/var/log/centreon-broker,rw
    # depends_on:
    #   - php
  php-init:
    build:
      context: php-init
      args:
        <<: *common-variables
    image: tpo76/php-init:24.04.0
    container_name: php-init
  php:
    build:
      context: php
      args:
        <<: *common-variables
    image: tpo76/php-fpm:24.04.0
    container_name: php
    hostname: php
    restart: always
    networks:
      - centreon_net
    volumes:
      - centreon-etc:/etc/centreon/:z,rw
      - centreon-share:/usr/share/centreon:z,rw
      - centreon-img:/usr/share/centreon/www/img/media/:z,rw
      - centreon-var:/var/lib/centreon:z,rw
      - centreon-cache:/var/cache/centreon/:z,rw
      - centreon-pack:/usr/share/centreon-packs/:rw
      - centplugin:/var/lib/centreon/centplugins/:z,rw
      - broker-etc:/etc/centreon-broker:z,rw
      - broker-log:/var/log/centreon-broker:z,ro
      - centengine-etc:/etc/centreon-engine/:z,rw
      - centreon-bin:/usr/local/share/applications/:z,ro
      - gorgone-cache:/var/cache/centreon-gorgone:z,ro
      - gorgone-etc:/etc/centreon-gorgone:z,rw
    depends_on:
      - database
  centengine:
    build:
      context: centengine
      args: 
        <<: *common-variables
    image: tpo76/centengine:24.04.0
    container_name: centengine
    hostname: centengine
    restart: always
    networks:
      - centreon_net
    volumes:
      - centreon-etc:/etc/centreon/:z,rw
      - centengine-etc:/etc/centreon-engine/:z,rw
      - centplugin:/var/lib/centreon/centplugins/:z,rw
      - broker-etc:/etc/centreon-broker:z,rw
      - centengine-log:/var/log/centreon-engine/:z,rw
      - centengine-var:/var/lib/centreon-engine/:z,rw
      - centreon-bin:/usr/local/share/applications/:z,rw
      - centreon-cache:/var/cache/centreon/:z,rw
    depends_on:
      - php
  apache:
    build:
      context: http
      args:
        <<: *common-variables
    image: tpo76/apache:24.04.0
    container_name: apache
    hostname: apache
    restart: always
    networks:
      - centreon_net
    ports:
      - 80:80
    volumes:
      - centreon-share:/usr/share/centreon:z,ro
      - centreon-img:/usr/share/centreon/www/img/media/:z,rw
    depends_on:
      - php
  gorgone:
    build:
      context: gorgone
      args:
        <<: *common-variables
    image: tpo76/gorgone:24.04.0
    container_name: gorgone
    hostname: gorgone
    restart: always
    networks:
      - centreon_net
    volumes:
      - centreon-etc:/etc/centreon:z,ro
      - centreon-var:/var/lib/centreon:z,rw
      - centreon-cache:/var/cache/centreon/:z,rw
      - centreon-bin:/usr/local/share/applications/:z,rw
      - centengine-etc:/etc/centreon-engine/:z,rw
      - broker-etc:/etc/centreon-broker:z,rw
      - centengine-log:/var/log/centreon-engine/:z,ro
      - gorgone-etc:/etc/centreon-gorgone:z,rw
      - gorgone-cache:/var/cache/centreon-gorgone:z,rw
      - gorgone-var:/var/lib/centreon-gorgone/:z,rw
      - centengine-var:/var/lib/centreon-engine/:z,rw
    depends_on:
      - php
  database:
    image: mariadb:10.5
    container_name: database
    hostname: database
    environment:
      <<: *common-variables
    restart: always
    networks:
      - centreon_net
    volumes:
      - ./database:/var/lib/mysql