apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: tpo76/apache:23.10.11
          resources: {}
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: TZ
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache-config
              mountPath: /app/
            - name: centreon-share
              mountPath: /usr/share/centreon
            - name: centreon-img
              mountPath: /usr/share/centreon/www/img/media/
      volumes:
        - name: apache-config
          configMap:
            name: apache-config
        - name: centreon-share
          persistentVolumeClaim:
            claimName: centreon-share
        - name: centreon-img
          persistentVolumeClaim:
            claimName: centreon-img