apiVersion: v1
kind: Service
metadata:
  name: cbd
spec:
  selector:
    app: cbd
  ports:
    - protocol: TCP
      port: 5669
      targetPort: 5669
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbd
  template:
    metadata:
      labels:
        app: cbd
    spec:
      containers:
        - name: cbd
          image: tpo76/broker:24.04.0
          imagePullPolicy: Always
          resources: {}
          env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: global-config
                key: TZ
          ports:
            - containerPort: 5669
          volumeMounts:
            - name: centreon-var
              mountPath: /var/lib/centreon
            - name: broker-etc
              mountPath: /etc/centreon-broker
            - name: broker-log
              mountPath: /var/log/centreon-broker
      volumes:
        - name: centreon-var
          persistentVolumeClaim:
            claimName: centreon-var
        - name: broker-etc
          persistentVolumeClaim:
            claimName: broker-etc
        - name: broker-log
          persistentVolumeClaim:
            claimName: broker-log