apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
spec:
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      containers:
      - name: php-init
        image: tpo76/php-init:24.04.0
        resources: {}
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: centreon-secret
                key: password
          - name: CENTREON_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: centreon-secret
                key: centreon_pwd
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: global-config
                key: TZ
          - name: https_proxy
            valueFrom:
              configMapKeyRef:
                name: global-config
                key: PROXY
          - name: http_proxy
            valueFrom:
              configMapKeyRef:
                name: global-config
                key: PROXY
          - name: no_proxy
            valueFrom:
              configMapKeyRef:
                name: global-config
                key: NO_PROXY
        volumeMounts:
          - name: centreon-etc
            mountPath: /etc/centreon
            readOnly: true
          - name: gorgone-etc
            mountPath: /etc/centreon-gorgone
      volumes:
        - name: centreon-etc
          persistentVolumeClaim:
            claimName: centreon-etc
        - name: gorgone-etc
          persistentVolumeClaim:
            claimName: gorgone-etc