apiVersion: v1
kind: Service
metadata:
  name: maintenance
spec:
  selector:
    app: maintenance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      containers:
      - name: maintenance
        image: httpd:latest
        resources: {}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: maintenance
          mountPath: /usr/local/apache2/htdocs/centreon/install/
      volumes:
      - name: maintenance
        configMap:
          name: maintenance-config

        