---
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: tpo76/apache:24.04.0
          imagePullPolicy: Always
          resources: {}
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: TZ
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache-config
              mountPath: /app/
            - name: centreon-share
              mountPath: /usr/share/centreon
            - name: centreon-img
              mountPath: /usr/share/centreon/www/img/media/
        - name: php
          image: tpo76/php-fpm:24.04.0
          imagePullPolicy: Always
          resources: {}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: centreon-secret
                  key: password
            - name: CENTREON_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: centreon-secret
                  key: centreon_pwd
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: TZ
            - name: https_proxy
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: PROXY
            - name: http_proxy
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: PROXY
            - name: no_proxy
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: NO_PROXY
          ports:
            - containerPort: 9042
          readinessProbe:
            tcpSocket:
              port: 9042
          volumeMounts:
            - name: php-session
              mountPath: /var/lib/php/sessions
            - name: php-cachedir
              mountPath: /var/lib/php/wsdlcache
            - name: php-config
              mountPath: /app/
            - name: centreon-etc
              mountPath: /etc/centreon
            - name: centreon-share
              mountPath: /usr/share/centreon
            - name: centreon-img
              mountPath: /usr/share/centreon/www/img/media
            - name: centreon-var
              mountPath: /var/lib/centreon
            - name: centreon-cache
              mountPath: /var/cache/centreon
            - name: centreon-pack
              mountPath: /usr/share/centreon-packs
            - name: centreon-centplugin
              mountPath: /var/lib/centreon/centplugins
            - name: broker-etc
              mountPath: /etc/centreon-broker
            - name: broker-log
              mountPath: /var/log/centreon-broker
            - name: centengine-etc
              mountPath: /etc/centreon-engine
            - name: centreon-bin
              mountPath: /usr/local/share/applications
            - name: gorgone-cache
              mountPath: /var/cache/centreon-gorgone
            - name: gorgone-etc
              mountPath: /etc/centreon-gorgone
      # hostAliases:
      #   - ip: "127.0.0.1"
      #     hostnames:
      #       - "central.k8s.centreon.com"	
      volumes:
        - name: php-session
          emptyDir: {}
        - name: php-cachedir
          emptyDir: {}
        - name: apache-config
          configMap:
            name: apache-config
        - name: php-config
          configMap:
            name: php-config
        - name: centreon-etc
          persistentVolumeClaim:
            claimName: centreon-etc
        - name: centreon-share
          persistentVolumeClaim:
            claimName: centreon-share
        - name: centreon-img
          persistentVolumeClaim:
            claimName: centreon-img
        - name: centreon-var
          persistentVolumeClaim:
            claimName: centreon-var
        - name: centreon-cache
          persistentVolumeClaim:
            claimName: centreon-cache
        - name: centreon-pack
          persistentVolumeClaim:
            claimName: centreon-pack
        - name: centreon-centplugin
          persistentVolumeClaim:
            claimName: centreon-centplugin
        - name: broker-etc
          persistentVolumeClaim:
            claimName: broker-etc
        - name: broker-log
          persistentVolumeClaim:
            claimName: broker-log
            readOnly: true
        - name: centengine-etc
          persistentVolumeClaim:
            claimName: centengine-etc
        - name: centreon-bin
          persistentVolumeClaim:
            claimName: centreon-bin
            readOnly: true
        - name: gorgone-cache
          persistentVolumeClaim:
            claimName: gorgone-cache
            readOnly: true
        - name: gorgone-etc
          persistentVolumeClaim:
            claimName: gorgone-etc