# centengine-etc
# centengine-log
# centengine-var
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: volume-centengine-etc
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 1Mi
#   volumeMode: Filesystem
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: standard
#   hostPath:
#     path: "/data/centengine-etc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centengine-etc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: volume-centengine-log
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 150Mi
#   volumeMode: Filesystem
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: standard
#   hostPath:
#     path: "/data/centengine-log"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centengine-log
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Mi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: volume-centengine-var
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 10Mi
#   volumeMode: Filesystem
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: standard
#   hostPath:
#     path: "/data/centengine-var"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centengine-var
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: volume-centengine-plugins
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 400Mi
#   volumeMode: Filesystem
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: standard
#   hostPath:
#     path: "/data/centengine-plugins"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centengine-plugins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
