## Volume section to claim
# centreon-share
# centreon-img
# centreon-etc
# centreon-var
# centreon-cache
# centreon-bin
# centreon-centplugin
# centreon-pack
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-centreon-share
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/data/centreon-share"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centreon-share
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-centreon-img
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/data/centreon-img"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centreon-img
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-centreon-etc
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/data/centreon-etc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centreon-etc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
### Graph Volume CHECK SIZE
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-centreon-var
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/data/centreon-var"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centreon-var
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-centreon-cache
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/data/centreon-cache"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centreon-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-centreon-bin
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/data/centreon-bin"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centreon-bin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-centreon-centplugin
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/data/centreon-centplugin"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centreon-centplugin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-centreon-pack
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/data/centreon-pack"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centreon-pack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi