# gorgone-etc
# gorgone-cache
# gorgone-var
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gorgone-etc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gorgone-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gorgone-var
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi