kind: Kustomization

resources:
- ingress/ingress.yaml
- configMap/mariadb-config.yaml
- configMap/apache-config.yaml
- configMap/php-config.yaml
- configMap/global-config.yaml
- configMap/centreon-secret.yaml
- configMap/smtp-config.yaml
- configMap/maintenance-config.yaml
- pvc/broker-pvc.yaml
- pvc/centengine-pvc.yaml
- pvc/centreon-pvc.yaml
- pvc/database-pvc.yaml
- pvc/gorgone-pvc.yaml
- deployement/apache-deployement.yaml
- deployement/maintenance-deployement.yaml
- deployement/cbd-deployement.yaml
- deployement/centengine-deployement.yaml
- deployement/database-deployement.yaml
- deployement/gorgone-deployement.yaml
- deployement/php-deployement.yaml
- cronjob/downtime-centreon.yaml
- cronjob/centacl.yaml
- cronjob/build-event.yaml
- cronjob/build-reporting.yaml
- cronjob/centreon-partitioning.yaml
- cronjob/centstorage-purge.yaml
