apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
  namespace: default
  labels:
    app: centreon
spec:
  tls:
  - hosts:
    - central.k8s.centreon.com
    secretName: tls-secret
  ingressClassName: nginx
  # defaultBackend:
  #   service:
  #     name: apache
  #     port:
  #       number: 80
  rules:
  - host: central.k8s.centreon.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache
            port:
              number: 80
      # - path: /centreon
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: apache
      #       port:
      #         number: 80
      # - path: /centreon/install/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: maintenance
      #       port:
      #         number: 80