#!/usr/bin/bash

POD_PHP=`sudo cat /proc/1/environ | tr '\0' '\n' | grep POD_PHP | cut -d= -f2`
POD_SOCK=`sudo cat /proc/1/environ | tr '\0' '\n' | grep POD_SOCK | cut -d= -f2`


podman --url $POD_SOCK exec --user apache $POD_PHP /usr/bin/php `dirname $0`/save_discovered_host.php $*
