apiVersion: batch/v1
kind: CronJob
metadata:
  name: build-event
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: build-event
            image: tpo76/cronbox:23.10.11
            env:
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: global-config
                    key: TZ
            command: ["/usr/share/centreon/cron/eventReportBuilder", "--config=/etc/centreon/conf.pm"]
            volumeMounts:
            - name: centreon-share
              mountPath: /usr/share/centreon
            - name: centreon-etc
              mountPath: /etc/centreon
            # Add other volume mounts as needed
          restartPolicy: OnFailure
          # serviceAccountName: centreon-user
          volumes:
          - name: centreon-share
            persistentVolumeClaim:
              claimName: centreon-share
              readOnly: true
          - name: centreon-etc
            persistentVolumeClaim:
              claimName: centreon-etc
              readOnly: true
      backoffLimit: 3
